"""
app/models/db_models.py
========================
SQLAlchemy ORM models that map Python classes to database tables.

Three tables:
    - ``documents``     — metadata for each uploaded PDF
    - ``chat_sessions`` — groups of messages belonging to one conversation
    - ``chat_messages`` — individual user/assistant messages within a session

All models inherit from ``Base`` (defined in ``app/database.py``) so that
``Base.metadata.create_all()`` automatically creates these tables.
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    DateTime,
    ForeignKey,
)
from sqlalchemy.orm import relationship

from app.database import Base


# ─────────────────────────────────────────────────────
# HELPER
# ─────────────────────────────────────────────────────

def _utcnow() -> datetime:
    """Return the current UTC time (timezone-aware)."""
    return datetime.now(timezone.utc)


# ─────────────────────────────────────────────────────
# DOCUMENT
# ─────────────────────────────────────────────────────

class Document(Base):
    """
    Represents an uploaded PDF document.

    Tracks file metadata (size, pages) and processing status so the
    frontend can show upload progress and disable querying until
    the document is fully embedded.

    Statuses:
        - ``processing`` — upload received, chunking/embedding in progress
        - ``ready``      — document is fully embedded and queryable
        - ``error``      — something went wrong during processing
    """

    __tablename__ = "documents"

    id: int = Column(Integer, primary_key=True, autoincrement=True)

    # The stored filename on disk (may include a UUID prefix to avoid collisions)
    filename: str = Column(String(500), nullable=False)

    # The filename the user originally uploaded
    original_filename: str = Column(String(500), nullable=False)

    # File size in bytes
    file_size: int = Column(Integer, nullable=True)

    # Number of pages in the PDF
    page_count: int = Column(Integer, nullable=True)

    # Number of text chunks created from this document
    chunk_count: int = Column(Integer, nullable=True)

    # When the file was uploaded
    upload_date: datetime = Column(
        DateTime,
        default=_utcnow,
        nullable=False,
    )

    # Processing status: 'processing', 'ready', or 'error'
    status: str = Column(String(50), default="processing", nullable=False)

    def __repr__(self) -> str:
        return (
            f"<Document(id={self.id}, "
            f"original_filename='{self.original_filename}', "
            f"status='{self.status}')>"
        )


# ─────────────────────────────────────────────────────
# CHAT SESSION
# ─────────────────────────────────────────────────────

class ChatSession(Base):
    """
    A chat session (conversation thread).

    Each session has a UUID primary key (generated by the application,
    not by the database) and keeps track of when it was created/updated
    so the frontend can sort sessions by recency.

    Relationship:
        A session has many ``ChatMessage`` objects (``messages`` list).
    """

    __tablename__ = "chat_sessions"

    # UUID string generated by the application (e.g. uuid.uuid4().hex)
    id: str = Column(String(36), primary_key=True)

    # Human-readable title, auto-generated or set by the user
    title: str = Column(String(500), default="New Chat", nullable=False)

    created_at: datetime = Column(
        DateTime,
        default=_utcnow,
        nullable=False,
    )

    updated_at: datetime = Column(
        DateTime,
        default=_utcnow,
        onupdate=_utcnow,
        nullable=True,
    )

    # One-to-many: a session has many messages
    messages = relationship(
        "ChatMessage",
        back_populates="session",
        cascade="all, delete-orphan",  # deleting a session deletes its messages
        order_by="ChatMessage.created_at",
    )

    def __repr__(self) -> str:
        return f"<ChatSession(id='{self.id}', title='{self.title}')>"


# ─────────────────────────────────────────────────────
# CHAT MESSAGE
# ─────────────────────────────────────────────────────

class ChatMessage(Base):
    """
    A single message within a chat session.

    Stores the role (``user`` or ``assistant``), the message content,
    and optional JSON-encoded metadata about sources and document IDs
    used during retrieval.

    Fields ``sources`` and ``document_ids`` store JSON strings because
    SQLite doesn't have a native JSON column type.  The application
    serialises/deserialises them with ``json.dumps()``/``json.loads()``.
    """

    __tablename__ = "chat_messages"

    id: int = Column(Integer, primary_key=True, autoincrement=True)

    # FK to the session this message belongs to
    session_id: str = Column(
        String(36),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
    )

    # 'user' or 'assistant'
    role: str = Column(String(20), nullable=False)

    # The actual message text
    content: str = Column(Text, nullable=False)

    # JSON string: list of source references returned with the answer
    # Example: [{"document_id": 1, "page_number": 3, "chunk_text": "..."}]
    sources: str = Column(Text, nullable=True)

    # JSON string: list of document IDs that were queried
    # Example: [1, 3, 5]
    document_ids: str = Column(Text, nullable=True)

    created_at: datetime = Column(
        DateTime,
        default=_utcnow,
        nullable=False,
    )

    # Many-to-one back-reference to the session
    session = relationship("ChatSession", back_populates="messages")

    def __repr__(self) -> str:
        preview = self.content[:40] + "..." if len(self.content) > 40 else self.content
        return (
            f"<ChatMessage(id={self.id}, role='{self.role}', "
            f"content='{preview}')>"
        )
